name: Notification Checkbox PR

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Client Checkboxes are Checked
        id: check-client-checkbox
        run: |
          pull_request_body="${{ github.event.pull_request.body }}"
          client_section=$(echo "${pull_request_body}" | sed -n '/✨ Client/,/기존 코드에서 변경된 점이 있다면 설명해주세요./p')
          
          if echo "${client_section}" | grep -q "\- \[x\]"; then
            echo "client_checked=true" >> $GITHUB_ENV
          else
            echo "client_checked=false" >> $GITHUB_ENV
          fi

      - name: Send Discord Notification
        if: env.client_checked == 'true'
        env:
          WEB_HOOK: ${{ secrets.AN_DISCORD_WEB_HOOK }}
          AVATAR_URL: ${{ secrets.PR_NOTI_AVATAR_URL }}
        run: |
          PULL_REQUEST_TITLE="${{ github.event.pull_request.title }}"
          PULL_REQUEST_URL="${{ github.event.pull_request.html_url }}"
          AUTHOR_NAME="${{ github.event.pull_request.user.login }}"
          AUTHOR_AVATAR="${{ github.event.pull_request.user.avatar_url }}"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(jq -n \
                     --arg content "API 관련 수정 PR이 열렸습니다!" \
                     --arg username "메타몽" \
                     --arg avatar_url "$AVATAR_URL" \
                     --arg pull_request_title "$PULL_REQUEST_TITLE" \
                     --arg pull_request_url "$PULL_REQUEST_URL" \
                     --arg author_name "$AUTHOR_NAME" \
                     --arg author_avatar "$AUTHOR_AVATAR" \
                     '{
                        content: $content, 
                        username: $username, 
                        avatar_url: $avatar_url, 
                        embeds: [{
                          title: $pull_request_title, 
                          url: $pull_request_url,
                          author: {
                            name: $author_name,
                            icon_url: $author_avatar
                          }
                        }] 
                     }'
                  )" \
               "$WEB_HOOK"
